name = "beacon-cm"
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true

[[kv_namespaces]]
binding = "KV"
id = "3c41083adc4047108e4cd9ac912a16e2"				

[[d1_databases]]
binding = "DB"
database_name = "beacon-tunnel-db"
database_id = "c17b4997-81f9-458b-bc7d-07369726f5eb"