name = "beacon-cm"
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true

[[routes]]
pattern = "beacon.ssdxz.cc.cd/*"
zone_name = "ssdxz.cc.cd"

[vars]
ADMIN = "809341047Yang"

[[kv_namespaces]]
binding = "KV"
id = "08e0acf157184a189c5e1a14335603a5"				

[[d1_databases]]
binding = "DB"
database_name = "beacon-tunnel-db"
database_id = "c17b4997-81f9-458b-bc7d-07369726f5eb"

[[durable_objects.bindings]]
name = "TG_VERIFY_DO"
class_name = "TGVerifyDO"

[[migrations]]
tag = "v1"
new_classes = ["TGVerifyDO"]

[triggers]
crons = ["0 */6 * * *"]
